[Application]
EnableSystemTray = false
CloseToSystemTray = false
StartupPage = 'Albums'
SettingsTab = 'Experimental'
AllowMultiInstance = false
MaxImageCacheSizeMB = 50
SavePlayQueue = true
DefaultPlaylistID = ''
ShowTrackChangeNotification = false
FontNormalTTF = ''
FontBoldTTF = ''
UIScaleSize = 'Normal'

[[Servers]]
ServerType = 'Subsonic'
Hostname = 'https://music.kulak.us'
AltHostname = ''
Username = 'phil'
LegacyAuth = false
ID = '050009cc-d15d-4deb-b85e-758ddf9382cc'
Nickname = 'Home'
Default = true

[AlbumPage]
TracklistColumns = ['Artist', 'Time', 'Plays', 'Favorite', 'Rating']

[AlbumsPage]
SortOrder = 'Recently Added'

[ArtistPage]
InitialView = 'Discography'
TracklistColumns = ['Album', 'Time', 'Plays', 'Favorite', 'Rating']

[FavoritesPage]
InitialView = 'Albums'
TracklistColumns = ['Artist', 'Album', 'Time', 'Plays']

[NowPlayingPage]
TracklistColumns = ['Artist', 'Album', 'Time', 'Plays']

[PlaylistPage]
TracklistColumns = ['Artist', 'Album', 'Time', 'Plays']

[PlaylistsPage]
InitialView = 'List'

[TracksPage]
TracklistColumns = ['Artist', 'Album', 'Time', 'Plays']

[LocalPlayback]
AudioDeviceName = 'auto'
AudioExclusive = false
InMemoryCacheSizeMB = 30
Volume = 80
EqualizerEnabled = false
EqualizerPreamp = 0.0
GraphicEqualizerBands = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[Scrobbling]
Enabled = true
ThresholdTimeSeconds = 240
ThresholdPercent = 50

[ReplayGain]
Mode = 'album'
PreampGainDB = 0.0
PreventClipping = true

[Transcoding]
ForceRawFile = false

[Theme]
ThemeFile = ''
Appearance = 'Dark'
