#!/usr/bin/env bash

riverctl map normal Super Return spawn 'alacritty -e fish'
riverctl map normal Super P spawn 'firefox'
riverctl map normal Super D spawn 'wofi -a -b -I -modi drun --show drun'
riverctl map normal Super E spawn 'wofi-emoji'
riverctl map normal Super X spawn 'wofi-power'
riverctl map normal Super N spawn 'nemo'
riverctl map normal Control Space spawn 'makoctl dismiss'
riverctl map normal Control+Shift Space spawn 'makoctl dismiss --all'

# Screenshots
riverctl map normal Super+Shift C spawn \
    'mkdir -p $HOME/Screenshots && slurp | grim -g - $HOME/Screenshots/$(date +"%Y-%m-%d-%H%M%S.png")'

# Popup Terminal
riverctl map normal Super+Shift Return spawn 'alacritty --class floating -e fish'
riverctl float-filter-add app-id 'floating'

# Close the focused view
riverctl map normal Super W close

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super M zoom

# Super+H and Super+L to decrease/increase the main ratio of filtile
riverctl map normal Super H send-layout-cmd filtile "main-ratio -5"
riverctl map normal Super L send-layout-cmd filtile "main-ratio +5"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 6)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-6] to focus tag [0-5]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-6] to tag focused view with tag [0-5]
    riverctl map normal Super+Shift $i set-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Define a couple special worspaces
riverctl map normal Super S toggle-focused-tags $((1 << 6))
riverctl map normal Super+Shift S set-view-tags $((1 << 6))

riverctl map normal Super V set-focused-tags $((1 << 7))
riverctl map normal Super+Shift V set-view-tags $((1 << 7))

riverctl map normal Super Minus toggle-focused-tags $((1 << 8))
riverctl map normal Super+Shift Minus set-view-tags $((1 << 8))

# Super+Space to toggle float
riverctl map normal Super+Shift Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Layout manager
riverctl map normal Super Z send-layout-cmd filtile "swap"
riverctl map normal Super C send-layout-cmd filtile "pad"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with wireplumber
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%-'
    riverctl map $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# My config that makes me happy
riverctl attach-mode bottom
riverctl focus-follows-cursor disabled
riverctl hide-cursor timeout 4000

# Inputs (maybe have this scroll all pointers someday)
riverctl input pointer-1149-8257-Kensington_Slimblade_Trackball scroll-method button
riverctl input pointer-1149-8257-Kensington_Slimblade_Trackball scroll-button BTN_SIDE
riverctl input pointer-1149-8257-Kensington_Slimblade_Trackball accel-profile adaptive
riverctl input pointer-1149-8257-Kensington_Slimblade_Trackball natural-scroll enabled

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0xbec7c7
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 30 200

# Floaty bits
riverctl float-filter-add app-id 'sublime_merge'
riverctl float-filter-add app-id 'pavucontrol'
riverctl float-filter-add app-id '.sublime-music-wrapped'
riverctl float-filter-add app-id 'imv'
riverctl float-filter-add app-id 'mpv'

# Anything specific to this machine
test -f ~/.config/river/host && source ~/.config/river/host

# Set the default layout generator to be filtile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout filtile
filtile &

swaybg -i wallpaper.png -m fill &
waybar &

dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP 
systemctl --user stop river-session.target
systemctl --user start river-session.target
