# The following line includes sensible defaults from the file
# .defaults.  You can override these defaults by appending
# configuration options to this file.  See the .defaults file or the
# jai(1) man page for details.

conf .defaults

unsetenv *_KEY
unsetenv *_PASS

