# The following line includes sensible defaults from the file
# .defaults.  You can override these defaults by appending
# configuration options to this file.  See the .defaults file or the
# jai(1) man page for details.

conf .defaults

# agent memory files
dir agents

# directories that are version controlled; go ham
dir Projects
dir vevo
dir nix

# directories that are needed for building and testing
dir .cargo
dir .m2
dir .gradle
dir .config/jgit

# settings that should punch through
dir .pi
dir .agent-browser

# rootless Docker socket for docker compose
dir /run/user/1000
setenv XDG_RUNTIME_DIR=/run/user/1000/docker.sock
setenv DOCKER_HOST=unix:///run/user/1000/docker.sock

setenv JAVA_TOOL_OPTIONS=-Djava.awt.headless=true -Duser.home=/home/phil
setenv GRADLE_USER_HOME=/home/phil/.gradle

unsetenv *_KEY
unsetenv *_PASS
setenv NEXUS_PASSWORD
